name: youtube_dl
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dio: ^5.7.0
  flutter_hls_parser: ^2.0.1
  html: ^0.15.4
  m3u8: ^1.0.0
  youtube_explode_dart: ^2.3.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
